server:
  port: 33004
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /backend

spring:
  datasource: #DB관련 설정
    url: jdbc:h2:tcp://localhost/~/hello
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties.hibernate:
      show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    property-naming-strategy: SNAKE_CASE #Java객체 <-> JSON 변환시 사용할 전략설정